version: "3.7"
services:
    angular-service:
        image: frontend
        container_name: frontendservice
        build: ./Frontend
        ports:
           - "4200:80"

    backend-server:
        image: backend
        restart: always
        container_name: springbackend
        build: ./Backend/DeviceAPI
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/DeviceReservationSystem
        ports:
            - "8081:8081"
        depends_on: 
          - db
        links:
          - angular-service

    db: 
        image: mysql
        restart: always
        container_name: mysqldb
        environment: 
          - MYSQL_DATABASE=DeviceReservationSystem
          - MYSQL_ROOT_USERNAME=root
          - MYSQL_ROOT_PASSWORD=Ness@123
        ports:
          - "3307:3306" 
        volumes: 
          - my-db= '/var/lib/mysql' 

volumes:
  my-db: