version: "3.7"
services:
    angular-service:
        image: frontend
        build: ./Frontend
        ports:
           - "4200:80"

    rest-api:
        image: rest-api
        build: /home/roshni/Downloads/adding_JPA
        ports:
            - "9090:8080"
        links:
            - angular-service
 