version: "3.7"
services:
    angular-service:
        image: frontend
        build: ./Frontend
        ports:
           - "4200:80"

    rest-api:
        image: rest-api
        build: ./Backend/SpringSecurityJWT
        ports:
            - "9090:8080"
        links:
            - angular-service
        depends_on:
            - mysqldb
    
    mysqldb:
        image: mysql
        build: ./MySQL
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mysqldb