version: "2" # need depends_on
services:
 # mysqldbContainer:
    #     image: mysqldb
    #     build: ./MySQL
    #     ports: 
    #         - "3306:3306"
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    #         - MYSQL_DATABASE=root
    
    angular-service:
        image: frontend
        build: ./Frontend
        ports:
           - "4200:80"
    
    db: 
        image: mysql
        container_name: mysql-db
        # restart: always
        environment: 
          - MYSQL_ROOT_USERNAME=root
          - MYSQL_ROOT_PASSWORD=Ness@123
        ports:
          - "3307:3306" #internal and external port mapping
        expose:
          - "3307"  #exposed port 
        # volumes: 
        #   - my-db= '/var/lib/mysql' #internal volumne

    adminer:
      image: adminer
      restart: always
      ports:
        - 9000:8080

    # rest-api:
    #     image: rest-api
    #     build: ./Backend/SB_Security_JWT_v2.7
    #     ports:
    #         - "8081:8080"
    #     links:
    #         - angular-service
    #     depends_on:
    #         - db

# volumes:
#   my-db: