version: "3.7"
services:

    db: 
        image: mysql
        restart: always
        container_name: mysqldb
        environment: 
          - MYSQL_DATABASE=DeviceReservationSystem
          - MYSQL_ROOT_USERNAME=root
          - MYSQL_ROOT_PASSWORD=Ness@123
        ports:
          - "3307:3306" 
        volumes: 
          - my-db= '/var/lib/mysql' 

    adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 9000:8080

volumes:
  my-db: