version: "2"
services:

    
    db: 
        image: mysql
        container_name: mysql-db
        # restart: always
        environment: 
          - MYSQL_ROOT_USERNAME=root
          - MYSQL_ROOT_PASSWORD=Ness@123
        ports:
          - "3307:3306" #internal and external port mapping
        expose:
          - "3307"  #exposed port 
        volumes: 
          - my-db= '/var/lib/mysql' #internal volumne

    adminer:
      image: adminer
      restart: always
      ports:
        - 9000:8080

volumes:
  my-db: