version: '3.1'

services:
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=Ness@123
      - MYSQL_ROOT_USERNAME=root
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - my-db= '/var/lib/mysql'

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  my-db: